name = "cloudflare-saas-stack"
compatibility_date = "2024-09-03"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "recipe2go-db"
database_id = "864af66c-ed4d-4d30-94e5-7bac840cb956"
migrations_dir = "./drizzle"
